version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=postgres
    ports:
      - '54322:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local