version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${BBDD_USER}
      - POSTGRES_PASSWORD=${BBDD_PASS}
      - POSTGRES_MULTIPLE_DATABASES=${BBDD_BBDD}
    ports:
      - '54322:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
